

/*CAPITULO_PADRE*/


-- Se creo la vista de los capitulos padre que estan en estado 1

CREATE OR REPLACE VIEW FIDE_PROLEARN_FINAL_PROF.FIDE_CP_V AS
 SELECT 
  CAPITULO_PADRE_TB_ID_CP_PK ,
  NOMBRE_CAPITULO_PADRE,
  NUMERO_CAPITULO_PADRE,
  ESTADO_DELET_PADRE
  FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB
  WHERE ESTADO_DELET_PADRE = 1;
  COMMIT;
/


--- Procedimiento para buscar al Capitulo Padre mediante el id

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CP_FINDBYID_SP (
  P_ID_CAPITULO_PADRE IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CP_V
        WHERE CAPITULO_PADRE_TB_ID_CP_PK = P_ID_CAPITULO_PADRE;
        COMMIT; 
END;
/


---Se busca el ID del Curso y el Padre relacionado al Curso

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CAP_CP_X_CUR_GET_SP(
  P_ID_CURSO IN NUMBER,
  P_CAPITULOS_PADRES OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN P_CAPITULOS_PADRES FOR
    SELECT DISTINCT 
        CP.CAPITULO_PADRE_TB_ID_CP_PK,
        CP.NOMBRE_CAPITULO_PADRE,
        CP.NUMERO_CAPITULO_PADRE,
        CP.ESTADO_DELET_PADRE
    FROM FIDE_CAPITULO_PADRE_TB CP
    JOIN FIDE_CAPITULO_HIJO_TB CH ON CP.CAPITULO_PADRE_TB_ID_CP_PK = CH.ID_CAPITULO_PADRE
    JOIN FIDE_CAPITULO_X_CURSO_TB CC ON CH.CAPITULO_HIJO_TB_ID_CH_PK = CC.ID_CAPITULO
    WHERE CC.ID_CURSO = P_ID_CURSO
    ORDER BY CP.NUMERO_CAPITULO_PADRE;
END;
/



-- Procedimiento para modificar el estado de capitulo padre

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CP_DELET_SP(
  P_ID_CAPITULO_PADRE NUMBER
) AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB 
  SET ESTADO_DELET_PADRE = 0
  WHERE CAPITULO_PADRE_TB_ID_CP_PK = P_ID_CAPITULO_PADRE;
  COMMIT;
END;
/


-- Este procedimiento tiene un parámetro adicional P_ID_CAPITULO_PADRE que indica si se debe crear un
-- nuevo capítulo padre (si es 0) o actualizar uno existente (si es un valor diferente de 0).

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CP_SAVE_UPDATE_SP(
  P_ID_CAPITULO_PADRE IN NUMBER,
  P_NOMBRE_CAPITULO_PADRE IN VARCHAR2,
  P_NUMERO_CAPITULO_PADRE IN INT,
  P_ESTADO_DELET_PADRE IN NUMBER
) AS
BEGIN
  IF P_ID_CAPITULO_PADRE = 0 THEN
    INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB (
      NOMBRE_CAPITULO_PADRE,
      NUMERO_CAPITULO_PADRE
    ) VALUES (
      P_NOMBRE_CAPITULO_PADRE,
      P_NUMERO_CAPITULO_PADRE
    );
  ELSE
    UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB
    SET NOMBRE_CAPITULO_PADRE = P_NOMBRE_CAPITULO_PADRE,
        NUMERO_CAPITULO_PADRE = P_NUMERO_CAPITULO_PADRE,
        ESTADO_DELET_PADRE = P_ESTADO_DELET_PADRE
    WHERE CAPITULO_PADRE_TB_ID_CP_PK = P_ID_CAPITULO_PADRE;
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/

