CREATE TABLE FIDE_PROLEARN_FINAL_PROF.TESTI (
  PARA VARCHAR2(2)
);

/*CAPITULO_HIJO*/


--- Buscar ID Capitulo Hijo 

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_FINDBYID_SP (
    P_ID_CAPITULO_HIJO IN NUMBER,
    P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT 
            CAPITULO_HIJO_TB_ID_CH_PK,
            ID_CAPITULO_PADRE,
            NOMBRE_CAPITULO_HIJO,
            VIDEO_CAPITULO,
            NUMERO_CAPITULO_HIJO,
            ESTADO_HIJO_TB
        FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB CH
        WHERE CH.CAPITULO_HIJO_TB_ID_CH_PK = P_ID_CAPITULO_HIJO
        AND CH.ESTADO_HIJO_TB = 1;

    INSERT INTO FIDE_PROLEARN_FINAL_PROF.TESTI (PARA) VALUES ('A');
    COMMIT; 

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        OPEN P_RESULTADO FOR SELECT NULL FROM DUAL WHERE 1=0; 
END;    
/


---Se  busca el ID del Capitulo Padre y del Curso relacionado al Capitulo Hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.GET_CAPITULOS_HIJOS_SP(
  P_ID_CURSO IN NUMBER,
  P_ID_CAPITULO_PADRE IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT 
      CH.CAPITULO_HIJO_TB_ID_CH_PK,
      CH.ID_CAPITULO_PADRE,
      CH.NOMBRE_CAPITULO_HIJO,
      CH.VIDEO_CAPITULO,
      CH.NUMERO_CAPITULO_HIJO,
      CH.ESTADO_HIJO_TB
    FROM FIDE_CAPITULO_HIJO_TB CH
    JOIN FIDE_CAPITULO_X_CURSO_TB CC ON CH.CAPITULO_HIJO_TB_ID_CH_PK = CC.ID_CAPITULO
    WHERE CC.ID_CURSO = P_ID_CURSO
    AND CH.ID_CAPITULO_PADRE = P_ID_CAPITULO_PADRE
    ORDER BY CH.NUMERO_CAPITULO_HIJO;
END;
/


-- Procedimiento para actualizar el estado de capitulo hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.ACTUALIZAR_ESTADO_HIJO(
  P_ID_HIJO IN NUMBER,
  P_ESTADO IN NUMBER
) AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB
  SET ESTADO_HIJO_TB = P_ESTADO
  WHERE CAPITULO_HIJO_TB_ID_CH_PK = P_ID_HIJO
  AND EXISTS (
    SELECT 1
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB
    WHERE CAPITULO_HIJO_TB_ID_CH_PK = P_ID_HIJO
  );
END;
/


-- Procedimiento para actualizar la informacion de un capitulo hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MODIFICAR_CH_SP(
  P_ID_HIJO IN NUMBER,
  P_NOMBRE_CAPITULO_HIJO IN VARCHAR2,
  P_VIDEO_CAPITULO IN VARCHAR2,
  P_NUMERO_CAPITULO_HIJO IN INT
) AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB
  SET NOMBRE_CAPITULO_HIJO = P_NOMBRE_CAPITULO_HIJO,
      VIDEO_CAPITULO = P_VIDEO_CAPITULO,
      NUMERO_CAPITULO_HIJO = P_NUMERO_CAPITULO_HIJO
  WHERE CAPITULO_HIJO_TB_ID_CH_PK = P_ID_HIJO;
END;
/


-- Procedimiento para guardar un hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_SAVE_SP(
  P_ID_CAPITULO_PADRE IN FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB.ID_CAPITULO_PADRE%TYPE,
  P_NOMBRE_CAPITULO IN VARCHAR2,
  P_NUMERO_CAPITULO IN INT,
  P_VIDEO_CAPITULO IN VARCHAR2
) AS
BEGIN
  INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB (
  ID_CAPITULO_PADRE,
  NOMBRE_CAPITULO_HIJO,
  NUMERO_CAPITULO_HIJO,
  VIDEO_CAPITULO)
  VALUES (P_ID_CAPITULO_PADRE, P_NOMBRE_CAPITULO, P_NUMERO_CAPITULO, P_VIDEO_CAPITULO);
  COMMIT;
END;
/
