CREATE TABLE FIDE_PROLEARN_FINAL_PROF.TESTI (
  PARA VARCHAR2(2)
);



/*CAPITULO_PADRE*/

-- Procedimiento para eliminar un capitulo padre

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CP_DELET_SP(
  P_ID_CAPITULO_PADRE NUMBER
) AS
BEGIN

  DELETE FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB 
  WHERE ID_CAPITULO_PADRE = P_ID_CAPITULO_PADRE;
  
  DELETE FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB 
  WHERE CAPITULO_PADRE_TB_ID_CP_PK = P_ID_CAPITULO_PADRE;
  
  COMMIT;
END;
/


-- Crear procedimiento para crear un capitulo padre

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CP_SAVE_SP(
  P_NOMBRE_CAPITULO VARCHAR2,
  P_NUMERO_CAPITULO INT
) AS
  V_ID_CAPITULO_PADRE NUMBER;
BEGIN
  INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_PADRE_TB (
    NOMBRE_CAPITULO_PADRE,
    NUMERO_CAPITULO_PADRE
  ) VALUES (
    P_NOMBRE_CAPITULO,
    P_NUMERO_CAPITULO
  ) RETURNING CAPITULO_PADRE_TB_ID_CP_PK INTO V_ID_CAPITULO_PADRE;
  
  COMMIT;
END;
/


---Se obtiene los padre mediante el ID del curso

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.GET_CAP_PADRE_X_CURSO_SP(
  P_ID_CURSO IN NUMBER,
  P_CAPITULOS_PADRES OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN P_CAPITULOS_PADRES FOR
    SELECT DISTINCT CP.*
    FROM FIDE_CAPITULO_PADRE_TB CP
    JOIN FIDE_CAPITULO_HIJO_TB CH ON CP.CAPITULO_PADRE_TB_ID_CP_PK = CH.ID_CAPITULO_PADRE
    JOIN FIDE_CAPITULO_X_CURSO_TB CC ON CH.CAPITULO_HIJO_TB_ID_CH_PK = CC.ID_CAPITULO
    WHERE CC.ID_CURSO = P_ID_CURSO
    ORDER BY CP.NUMERO_CAPITULO_PADRE;
END;
/


 

