--------------------------PARTE MONTOS-------------------------------------------

--Crea la secuencia para la tabla de monto
CREATE SEQUENCE FIDE_PROLEARN_FINAL_PROF.ID_MONTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/

--Creacion de la tabla monto
CREATE TABLE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (
    MONTO_TB_ID_MT_PK NUMBER PRIMARY KEY,
    TIPO_SUSCRIPCION VARCHAR2(50) NOT NULL,
    PRECIO_PRINCIPAL NUMBER(10, 2) NOT NULL,
    ESTADO_PUBLICO_MT NUMBER(1) NOT NULL,
    ESTADO_DELET_MONTO NUMBER(1) NOT NULL,
    DESCUENTO NUMBER(5, 2) DEFAULT 0,
    PRECIO_CON_DESCUENTO NUMBER(10, 2) GENERATED ALWAYS AS (
        PRECIO_PRINCIPAL - (PRECIO_PRINCIPAL * DESCUENTO / 100)
    ) VIRTUAL,
    DESCRIPCION VARCHAR2(255)
);
/

-- Crear trigger para insertar valor del secuenciador
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_ID_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
  :NEW.MONTO_TB_ID_MT_PK := FIDE_PROLEARN_FINAL_PROF.ID_MONTO_SEQ.NEXTVAL;
END;
/

-- Crear trigger para establecer ESTADO en TRUE despues de la insercion
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_CURSO_ESTADO_PUBLICO_MT_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO_PUBLICO_MT := 1 ;
END;
/

-- Crear trigger para establecer ESTADO en TRUE despues de la insercion
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_ESTADO_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO_DELET_MONTO := 1 ;
END;
/

--Inserts de Montos
INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Mensual', 10.000, 0, 'Suscripción de un mes sin descuento');

INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Trimestral', 45.000, 15, 'Suscripción de tres meses con 15% de descuento');

INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Anual', 120.000, 35, 'Suscripción de un año con 35% de descuento');


--------------------------------Otros procedimientos----------------------------

-- Se creo la vista de Montos que estan en estado 1
CREATE OR REPLACE VIEW FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_V AS
SELECT 
  MONTO_TB_ID_MT_PK
  
FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
WHERE ESTADO_DELET_MONTO = 1;
/

--- Procedimiento para buscar montos mediante el id
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GET_BYID_SP (
  P_ID_MONTO IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
        WHERE MONTO_TB_ID_MT_PK = P_ID_MONTO;
    COMMIT;
END;
/

---Se busca el ID de tipo suscripcion y montos
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GETALL_BY_TIPO_SUSCRIPCION_SP(
  P_TIPO_SUSCRIPCION IN VARCHAR2,
  P_MONTOS OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_MONTOS FOR
    SELECT DISTINCT M.* 
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB M
    WHERE M.TIPO_SUSCRIPCION = P_TIPO_SUSCRIPCION
    ORDER BY M.PRECIO_PRINCIPAL;
END;
/

-- Procedimiento para elimnar a un monto
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_DELETE_SP(
  P_ID_MONTO NUMBER
) AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB 
  SET ESTADO_DELET_MONTO = 0
  WHERE MONTO_TB_ID_MT_PK = P_ID_MONTO;
  COMMIT;
END;
/

-- Procedimiento para listar todos los montos al publico
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GETALL_PUBLICO_SP(
  P_CURSOR OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN P_CURSOR FOR
  SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
  WHERE ESTADO_PUBLICO_MT = 1;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_UPSERT_SP(
  P_ID_MONTO IN NUMBER,
  P_TIPO_SUSCRIPCION IN VARCHAR2,
  V_ID_RESULTADO OUT NUMBER
) AS
  V_ID_NUEVO_MONTO NUMBER;
BEGIN
  IF P_ID_MONTO = 0 THEN
    INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (
      TIPO_SUSCRIPCION
    ) VALUES (
      P_TIPO_SUSCRIPCION
    ) RETURNING MONTO_TB_ID_MT_PK INTO V_ID_NUEVO_MONTO;
    
  ELSE
    UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
    SET TIPO_SUSCRIPCION = P_TIPO_SUSCRIPCION
    WHERE MONTO_TB_ID_MT_PK = P_ID_MONTO;
    
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/