CREATE TABLE FIDE_PROLEARN_FINAL_PROF.TESTI (
  PARA VARCHAR2(2)
);

/*CAPITULO_HIJO*/


--- Buscar ID Capitulo Hijo 

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_FINDBYID_SP (
    P_ID_CAPITULO_HIJO IN NUMBER,
    P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT 
            CAPITULO_HIJO_TB_ID_CH_PK,
            ID_CAPITULO_PADRE,
            NOMBRE_CAPITULO_HIJO,
            VIDEO_CAPITULO,
            NUMERO_CAPITULO_HIJO,
            ESTADO_HIJO_TB
        FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB CH
        WHERE CH.CAPITULO_HIJO_TB_ID_CH_PK = P_ID_CAPITULO_HIJO;

    INSERT INTO FIDE_PROLEARN_FINAL_PROF.TESTI (PARA) VALUES ('A');
    COMMIT; 

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        OPEN P_RESULTADO FOR SELECT NULL FROM DUAL WHERE 1=0; 
END;    
/


---Se  busca el ID del Capitulo Padre y del Curso relacionado al Capitulo Hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.GET_CAPITULOS_HIJOS_SP(
  P_ID_CURSO IN NUMBER,
  P_ID_CAPITULO_PADRE IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
  OPEN P_RESULTADO FOR
    SELECT 
      CH.CAPITULO_HIJO_TB_ID_CH_PK,
      CH.ID_CAPITULO_PADRE,
      CH.NOMBRE_CAPITULO_HIJO,
      CH.VIDEO_CAPITULO,
      CH.NUMERO_CAPITULO_HIJO,
      CH.ESTADO_HIJO_TB
    FROM FIDE_CAPITULO_HIJO_TB CH
    JOIN FIDE_CAPITULO_X_CURSO_TB CC ON CH.CAPITULO_HIJO_TB_ID_CH_PK = CC.ID_CAPITULO
    WHERE CC.ID_CURSO = P_ID_CURSO
    AND CH.ID_CAPITULO_PADRE = P_ID_CAPITULO_PADRE
    ORDER BY CH.NUMERO_CAPITULO_HIJO;
END;
/


-- Procedimiento para guardar un hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_SAVE_SP(
  P_ID_CAPITULO_PADRE IN FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB.ID_CAPITULO_PADRE%TYPE,
  P_NOMBRE_CAPITULO IN VARCHAR2,
  P_NUMERO_CAPITULO IN INT
) AS
BEGIN
  INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB (
  ID_CAPITULO_PADRE,
  NOMBRE_CAPITULO_HIJO,
  NUMERO_CAPITULO_HIJO)
  VALUES (P_ID_CAPITULO_PADRE, P_NOMBRE_CAPITULO, P_NUMERO_CAPITULO);
  COMMIT;
END;
/

BEGIN
  FIDE_PROLEARN_FINAL_PROF.CH_SAVE_SP(
    P_ID_CAPITULO => P_ID_CAPITULO_PADRE,
    P_NOMBRE_CAPITULO => P_NOMBRE_CAPITULO,
    P_ID_CURSO => P_ID_CURSO
  );
END;
/

-- Procedimiento para eliminar un capitulo hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_DELETE_SP(
  P_ID_CAPITULO_HIJO IN FIDE_CAPITULO_HIJO_TB.CAPITULO_HIJO_TB_ID_CH_PK%TYPE
) AS
BEGIN

  DELETE FROM FIDE_CAPITULO_HIJO_TB
  WHERE CAPITULO_HIJO_TB_ID_CH_PK = P_ID_CAPITULO_HIJO;
  
  COMMIT;
END;
/

BEGIN
  FIDE_PROLEARN_FINAL_PROF.CH_DELETE_SP(P_ID_CAPITULO_HIJO => :P_ID_CAPITULO_HIJO);
END;
/




