



--------------------------------Otros procedimientos----------------------------

-- Se creo la vista de Montos que estan en estado 1
CREATE OR REPLACE VIEW FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_V AS
SELECT 
  MONTO_TB_ID_MT_PK,
  NOMBRE,
  MONTO,
  DESCUENTO,
  MONTO_SIN_DESCUENTO,
  ESTADO_PUBLICO_MONTO
FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
WHERE ESTADO_DELET_MONTO = 1;

--- Procedimiento para buscar montos mediante el id
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GET_BYID_SP (
  P_ID_MONTO IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_V
        WHERE MONTO_TB_ID_MT_PK = P_ID_MONTO;
    COMMIT;
END;
/

---Se trae los montos publicos
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GETALL_PUBLICO_SP(
  P_MONTOS OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_MONTOS FOR
    SELECT *
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_V
    WHERE ESTADO_PUBLICO_MONTO = 1;
END;
/

---Se trae los montos
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_GETALL_ADMIN_SP(
  P_MONTOS OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_MONTOS FOR
    SELECT *
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_V;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_DELET_SP(
  P_ID_MONTO IN NUMBER
)
AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
  SET ESTADO_DELET_MONTO = 0
  WHERE MONTO_TB_ID_MT_PK = P_ID_MONTO;
  COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.MONTO_UPSERT_SP(
  P_MONTO_TB_ID_MT_PK IN NUMBER,
  P_NOMBRE IN VARCHAR2,
  P_MONTO IN NUMBER,
  P_DESCUENTO IN NUMBER,
  P_MONTO_SIN_DESCUENTO IN NUMBER,
  P_INTERVALO IN DATE,
  P_ESTADO_PUBLICO IN NUMBER
) AS
BEGIN
  IF P_MONTO_TB_ID_MT_PK = 0 THEN
    INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (
      NOMBRE,
      MONTO,
      DESCUENTO,
      MONTO_SIN_DESCUENTO,
      INTERVALO,
      ESTADO_PUBLICO_MONTO,
      ESTADO_DELET_MONTO
    ) VALUES (
      P_NOMBRE,
      P_MONTO,
      P_DESCUENTO,
      P_MONTO_SIN_DESCUENTO,
      P_INTERVALO,
      P_ESTADO_PUBLICO,
      1
    );
  ELSE
    UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
    SET NOMBRE = P_NOMBRE,
        MONTO = P_MONTO,
        DESCUENTO = P_DESCUENTO,
        MONTO_SIN_DESCUENTO = P_MONTO_SIN_DESCUENTO,
        INTERVALO = P_INTERVALO,
        ESTADO_PUBLICO_MONTO = P_ESTADO_PUBLICO
    WHERE MONTO_TB_ID_MT_PK = P_MONTO_TB_ID_MT_PK;
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/
