--------------------------PARTE MONTOS-------------------------------------------

--Crea la secuencia para la tabla de monto
CREATE SEQUENCE FIDE_PROLEARN_FINAL_PROF.ID_MONTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;
/

--Creacion de la tabla monto
CREATE TABLE FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (
    MONTO_TB_ID_MT_PK NUMBER PRIMARY KEY,
    TIPO_SUSCRIPCION VARCHAR2(50) NOT NULL,
    PRECIO_PRINCIPAL NUMBER(10, 2) NOT NULL,
    ESTADO_PUBLICO_MT NUMBER(1) NOT NULL,
    ESTADO_DELET_MONTO NUMBER(1) NOT NULL,
    DESCUENTO NUMBER(5, 2) DEFAULT 0,
    PRECIO_CON_DESCUENTO NUMBER(10, 2) GENERATED ALWAYS AS (
        PRECIO_PRINCIPAL - (PRECIO_PRINCIPAL * DESCUENTO / 100)
    ) VIRTUAL,
    DESCRIPCION VARCHAR2(255)
);
/

-- Crear trigger para insertar valor del secuenciador
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_ID_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
  :NEW.MONTO_TB_ID_MT_PK := FIDE_PROLEARN_FINAL_PROF.ID_MONTO_SEQ.NEXTVAL;
END;
/

-- Crear trigger para establecer ESTADO en TRUE despues de la insercion
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_CURSO_ESTADO_PUBLICO_MT_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO_PUBLICO_MT := 1 ;
END;
/

-- Crear trigger para establecer ESTADO en TRUE despues de la insercion
CREATE OR REPLACE TRIGGER FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_ESTADO_TRG
BEFORE INSERT ON FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADO_DELET_MONTO := 1 ;
END;
/

--Inserts de Montos
INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Mensual', 10.000, 0, 'Suscripción de un mes sin descuento');

INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Trimestral', 45.000, 15, 'Suscripción de tres meses con 15% de descuento');

INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB (TIPO_SUSCRIPCION, PRECIO_PRINCIPAL, DESCUENTO, DESCRIPCION)
VALUES ('Anual', 120.000, 35, 'Suscripción de un año con 35% de descuento');


--------------------------------Otros procedimientos----------------------------
