
-------------------Otros procedimientos-----------------------------------------

-- Se creo la vista de facturas que estan en estado 1
CREATE OR REPLACE VIEW FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_V AS
SELECT 
  FACTURA_TB_ID_FACTURA_PK,
  USUARIO_ID,
  MONTO_ID,
  FECHA_PAGO,
  FECHA_EXPIRACION
FROM FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_TB
WHERE ESTADO_DELET_FACTURA = 1;

--- Procedimiento para buscar facturas mediante el id
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.FACTURA_GET_BYID_SP (
  P_ID_FACTURA IN NUMBER,
  P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_V
        WHERE FACTURA_TB_ID_FACTURA_PK = P_ID_FACTURA;
    COMMIT;
END;
/



CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.FACTURA_GET_BYUSER_SP(
    P_ID_USER IN NUMBER,
    P_RESULTADO OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_RESULTADO FOR
    SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_V 
    WHERE USUARIO_ID = P_ID_USER
    ORDER BY FECHA_PAGO DESC;
END;
/


CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.FACTURA_GETALL_SP(
  P_FACTURAS OUT SYS_REFCURSOR
) AS
BEGIN
  OPEN P_FACTURAS FOR
  SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_V;
END;
/


-- Procedimiento para elimnar a una factura
CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.FACTURA_DELETE_SP(
  P_ID_FACTURA NUMBER
) AS
BEGIN
  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_TB 
  SET ESTADO_DELET_FACTURA = 0
  WHERE FACTURA_TB_ID_FACTURA_PK = P_ID_FACTURA;
  COMMIT;
END;
/



CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.FACTURA_CREAR_SP(
   P_MONTO_ID NUMBER ,
   P_USUARIO_ID NUMBER
)
AS
  V_ROL_ID NUMBER;
  V_FECHA_PAGO DATE := SYSDATE;
  V_NOMBRE_USUARIO VARCHAR2(50);
  V_INTERVALO INTERVAL YEAR TO MONTH;
  V_MONTO_TB FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB%ROWTYPE;
  V_FECHA_EXPIRACION DATE;
BEGIN
  INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_TB (MONTO_ID,USUARIO_ID, FECHA_PAGO)
  VALUES ( P_MONTO_ID,P_USUARIO_ID, SYSDATE);
  COMMIT;

  BEGIN
    SELECT ROL_ID, NOMBRE INTO V_ROL_ID, V_NOMBRE_USUARIO
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_USUARIOS_TB
    WHERE USUARIOS_TB_ID_USER_PK = P_USUARIO_ID;
  END;

  BEGIN
    SELECT * INTO V_MONTO_TB
    FROM FIDE_PROLEARN_FINAL_PROF.FIDE_MONTO_TB
    WHERE MONTO_TB_ID_MT_PK = P_MONTO_ID;
  END;

  V_INTERVALO := V_MONTO_TB.INTERVALO;

  V_FECHA_PAGO := SYSDATE;
  V_FECHA_EXPIRACION := V_FECHA_PAGO + V_INTERVALO;

  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_FACTURA_TB
  SET FECHA_EXPIRACION = V_FECHA_EXPIRACION
  WHERE USUARIO_ID = P_USUARIO_ID;
  COMMIT;

  UPDATE FIDE_PROLEARN_FINAL_PROF.FIDE_USUARIOS_TB
  SET ROL_ID = 3,
      VENCIMIENTO_SUSCRIPCION = V_FECHA_EXPIRACION
  WHERE USUARIOS_TB_ID_USER_PK = P_USUARIO_ID;
  COMMIT;
  
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/   