CREATE TABLE FIDE_PROLEARN_FINAL_PROF.TESTI (
  PARA VARCHAR2(2)
);



/*CAPITULO_HIJO*/



CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_FINDBYID_SP (
    P_ID_CAPITULO_HIJO IN NUMBER,
    P_RESULTADO OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULTADO FOR
        SELECT * FROM FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB CH
        WHERE CH.CAPITULO_HIJO_TB_ID_CH_PK = P_ID_CAPITULO_HIJO;

    INSERT INTO FIDE_PROLEARN_FINAL_PROF.TESTI (PARA) VALUES ('A');
    COMMIT; 

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        OPEN P_RESULTADO FOR SELECT NULL FROM DUAL WHERE 1=0; 
END;    
/




-- Procedimiento para guardar un hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_SAVE_SP(
  P_ID_CAPITULO_PADRE IN FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB.ID_CAPITULO_PADRE%TYPE,
  P_NOMBRE_CAPITULO IN VARCHAR2,
  P_NUMERO_CAPITULO IN INT
) AS
BEGIN
  INSERT INTO FIDE_PROLEARN_FINAL_PROF.FIDE_CAPITULO_HIJO_TB (
  ID_CAPITULO_PADRE,
  NOMBRE_CAPITULO_HIJO,
  NUMERO_CAPITULO_HIJO)
  VALUES (P_ID_CAPITULO_PADRE, P_NOMBRE_CAPITULO, P_NUMERO_CAPITULO);
  COMMIT;
END;
/


-- Procedimiento para eliminar un capitulo hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_DELETE_SP(
  P_ID_CAPITULO_HIJO IN FIDE_CAPITULO_HIJO_TB.CAPITULO_HIJO_TB_ID_CH_PK%TYPE
) AS
BEGIN

  DELETE FROM FIDE_CAPITULO_HIJO_TB
  WHERE CAPITULO_HIJO_TB_ID_CH_PK = P_ID_CAPITULO_HIJO;
  
  COMMIT;
END;
/


-- Procedimiento para llamar a todos los capitulo hijo

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CAPITULOS_HIJOS_FIND_ALL AS
  CURSOR CUR_CAPITULOS_HIJOS IS
    SELECT *
    FROM FIDE_CAPITULO_HIJO_TB;
  
  V_REGISTRO FIDE_CAPITULO_HIJO_TB%ROWTYPE;
BEGIN
  OPEN CUR_CAPITULOS_HIJOS;
  
  DBMS_OUTPUT.PUT_LINE('ID  || Nombre ');
  
  LOOP
    FETCH CUR_CAPITULOS_HIJOS INTO V_REGISTRO;
    EXIT WHEN CUR_CAPITULOS_HIJOS%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE(V_REGISTRO.CAPITULO_HIJO_TB_ID_CH_PK || ' || ' || V_REGISTRO.NOMBRE_CAPITULO_HIJO );
  END LOOP;
  
  CLOSE CUR_CAPITULOS_HIJOS;
END APITULOS_HIJOS_FIND_ALL;
/



CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.CH_CP_FIND_ID_SP AS
  CURSOR CUR_CAPITULOS_HIJOS IS
    SELECT *
    FROM FIDE_CAPITULO_HIJO_TB;
  
  V_REGISTRO FIDE_CAPITULO_HIJO_TB%ROWTYPE;
BEGIN
  OPEN CUR_CAPITULOS_HIJOS;
  
  DBMS_OUTPUT.PUT_LINE('ID padre');
  
  LOOP
    FETCH CUR_CAPITULOS_HIJOS INTO V_REGISTRO;
    EXIT WHEN CUR_CAPITULOS_HIJOS%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE( v_registro.ID_CAPITULO_PADRE );
  END LOOP;
  
  CLOSE CUR_CAPITULOS_HIJOS;
END CH_CP_FIND_ID_SP;
/

BEGIN
  FIDE_PROLEARN_FINAL_PROF.CH_CP_FIND_ID_SP;
END;
/


---Se obtiene los hijos mediante el ID del curso y del padre

CREATE OR REPLACE PROCEDURE FIDE_PROLEARN_FINAL_PROF.GET_CAPITULOS_HIJOS_SP(
  p_id_curso IN NUMBER,
  p_id_capitulo_padre IN NUMBER
)
AS
  CURSOR c_capitulos_hijos IS
    SELECT ch.*
    FROM FIDE_CAPITULO_HIJO_TB ch
    JOIN FIDE_CAPITULO_X_CURSO_TB cc ON ch.CAPITULO_HIJO_TB_ID_CH_PK = cc.ID_CAPITULO
    WHERE cc.ID_CURSO = p_id_curso
    AND ch.ID_CAPITULO_PADRE = p_id_capitulo_padre
    ORDER BY ch.NUMERO_CAPITULO_HIJO;
BEGIN
  FOR r_capitulo_hijo IN c_capitulos_hijos LOOP
    NULL;
  END LOOP;
END;
/



